apiVersion: v2
name: todo-app
description: A Helm chart for Todo Application
type: application
version: 1.0.0
appVersion: "1.0.0"
maintainers:
  - name: Piyush Bajpai
    email: your-email@example.com
